### ISSUE TITLE
Add Slack notifications

### ISSUE THREAD

**Issue by Smismi11** [robre/jsmon#1]
Would it be possible to get notified via slack too?

**Comment by robre** [comment]
Hi, yes this should be easily possible. You can send slack notifications with a simple web hook. I will add this in the future.

**Comment by smtp-25** [comment]
+1
Can you add future to get notified by email too?
Thank you

**Comment by abdoulhacker** [comment]
It can be really nice if you add slack

**Comment by yassineaboukir** [comment]
Hi - I am still testing this tool but I've got Slack to work. Might send a PR later on ;)

**Comment by yassineaboukir** [comment]
Hi - I replaced Telegram with Slack notifications in my own fork. See: https://github.com/yassineaboukir/jsmon

If @robre is interested, I can send a new PR that supports both Telegram and Slack.

**Comment by abdulsec** [comment]
Thank you @yassineaboukir
