### ISSUE TITLE
pip cant install decouple 

### ISSUE THREAD

**Issue by rew1nter** [robre/jsmon#15]
on `python3 jsmon.py`:
![Screenshot_945](https://user-images.githubusercontent.com/64508791/135720198-eb359d6a-3c70-4c51-8105-0f55fb27d4be.png)

on `pip install decouple`:
![Screenshot_944](https://user-images.githubusercontent.com/64508791/135720220-14539676-35cd-471e-b00f-5041192b1989.png)

how to fix this?

**Comment by yassineaboukir** [comment]
First of all, you're using `python3` so you should be using `pip3`. 

To install the missing package try:

>pip3 install python-decouple

**Comment by rew1nter** [comment]
FYI on windows you dont have to write `pip3` explicitly. Moreover I didnt have python2 installed. It seems to be fixed now somehow, so cheers.
![Screenshot_1003](https://user-images.githubusercontent.com/64508791/142860535-8552e49a-d3f7-4be8-a6e1-75acfca3f179.png)
