### ISSUE TITLE
Is this tested using cronjob??

### ISSUE THREAD

**Issue by maverickNerd** [robre/jsmon#5]
With cronjob configured as mentioned in readme, lets say `@daily python3 /root/tools/jsmon/jsmon.py`

this point of the code: 
```
allendpoints = get_endpoint_list('targets')
print(allendpoints)   # endpoint will come as {} because targets is not in $HOME but in jsmon dir here: /root/tools/jsmon/
```
I am able to get it working by modifying to full path in jsmon.py but it is not flexible, not sure how can we check jsmon dir path and configure all paths in jsmon.py with that full path dynamically.

Here is some part of my change which I did  to get it working with cronjob
```
-    oldlines = open("downloads/{}".format(old), "r").readlines()
-    newlines = open("downloads/{}".format(new), "r").readlines()
+    oldlines = open("/root/tools/jsmon/downloads/{}".format(old), "r").readlines()
+    newlines = open("/root/tools/jsmon/downloads/{}".format(new), "r").readlines()
     oldbeautified = jsbeautifier.beautify("".join(oldlines), opt).splitlines()
     newbeautified = jsbeautifier.beautify("".join(newlines), opt).splitlines()
     # print(oldbeautified)
@@ -123,8 +123,8 @@ def main():
         print("Please Set Up your Telegram Token And Chat ID!!!")
         exit(1)
         
-    allendpoints = get_endpoint_list('targets')
-    # print(allendpoints)
+    allendpoints = get_endpoint_list("/root/tools/jsmon/targets")
+    print(allendpoints)
 ```

**Comment by robre** [comment]
Yea i realized cronjobs actually have their own path variable so it wouldnt work as i described. Ill have to push an update with a fix

**Comment by maverickNerd** [comment]
Cool, I was trying to message you on twitter, but your DMs are off, one more issue, currently targets/ dir has .gitignore file which is also breaking this issue, check the other issues, I explained there why. 

Please let me know on this issue, once you get the path issue fixed.

**Comment by robre** [comment]
Yep i saw that too. For the cronjob a workaround which im using is to call a shellscript which starts the python script

**Comment by yassineaboukir** [comment]
Hi,

I think inserting this line in crontab file should fix it:

```
0 */12 * * * cd /root/jsmon/ && /usr/bin/python jsmon.py 
```

This will run the cron job every 12 hours.

**Comment by yassineaboukir** [comment]
> Cool, I was trying to message you on twitter, but your DMs are off, one more issue, currently targets/ dir has .gitignore file which is also breaking this issue, check the other issues, I explained there why.
> 
> Please let me know on this issue, once you get the path issue fixed.

I sent following PR https://github.com/robre/jsmon/pull/6 to fix that issue.
